# Generated by Django 5.0.6 on 2024-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformationinfo',
            name='model_used',
            field=models.TextField(null=True),
        ),
    ]
